@startuml

skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
!pragma useVerticalIf on
start
:User enters person export command;
if () then ([all fields present])
    if () then ([index is valid])
        :Export command executes, person is shown as text;

    else ([else])
    :Error: Invalid index;
    stop
    endif
else ([else])
:Error: Invalid command format;
stop
endif
stop
@enduml
