@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package Views <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class UiManager
Class MainWindowController
Class TitleBarController
Class HelpDialogController
Class ResultDisplayController
Class PersonTreeViewController
Class MeetingTreeViewController
Class StatusBarFooterController
Class CommandBoxController
Class TimetableController
Class PersonCardController
Class MeetingCardController

note right of MainWindowController
  Most controllers:
  - implement UiPart interface
  - depend on ViewModel component
  - depend on Model component
end note
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindowController
MainWindowController *-down->  "1" TitleBarController 
MainWindowController *-down->  "1" CommandBoxController
MainWindowController *-down-> "1" ResultDisplayController
MainWindowController *-down-> "1" PersonTreeViewController
MainWindowController *-down-> "1" MeetingTreeViewController
MainWindowController *-down-> "1" StatusBarFooterController
MainWindowController *-down-> "1" TimetableController
MainWindowController *-down-> "1" HelpDialogController 

PersonTreeViewController -down-> "*" PersonCardController
MeetingTreeViewController -down-> "*" MeetingCardController

PersonTreeViewController -[hidden]left- HelpWindowController
HelpWindowController -[hidden]left- CommandBoxController
CommandBoxController -[hidden]left- ResultDisplayController
ResultDisplayController -[hidden]left- StatusBarFooterController
@enduml
