@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor VIEW_MODEL_COLOR_T4
skinparam classBackgroundColor VIEW_MODEL_COLOR

package ViewModel <<Rectangle>>{
Class MainViewModel
Class CommandBoxViewModel
Class ResultDisplayViewModel
Class PersonListViewModel
Class MeetingListViewModel
note right of MainViewModel
  Most view models:
  - Depend on Model component
end note
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> MainViewModel

MainViewModel *-down->  "1" CommandBoxViewModel
MainViewModel *-down-> "1" ResultDisplayViewModel
MainViewModel *-down-> "1" PersonListViewModel
MainViewModel *-down-> "1" MeetingListViewModel

MainViewModel -right-> Logic

ResultDisplayViewModel -[hidden]left- CommandBoxViewModel
PersonListViewModel -[hidden]left- ResultDisplayViewModel
MeetingListViewModel -[hidden]left- PersonListViewModel
@enduml
