@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor VIEW_MODEL_COLOR_T4
skinparam classBackgroundColor VIEW_MODEL_COLOR

package ViewModel <<Rectangle>>{
Class MainViewModel
Class CommandBoxViewModel
Class ResultDisplayViewModel
Class PersonListViewModel
Class MeetingListViewModel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

HiddenOutside ..> MainViewModel

MainViewModel *-down->  "1" CommandBoxViewModel
MainViewModel *-down-> "1" ResultDisplayViewModel
MainViewModel *-down-> "1" PersonListViewModel
MainViewModel *-down-> "1" MeetingListViewModel

MeetingListViewModel -down- Invisible
Invisible -right- Model
hide Invisible

CommandBoxViewModel -right> Model
ResultDisplayViewModel -right> Model
PersonListViewModel -right> Model
MeetingListViewModel -down> Model

MainViewModel -right-> Logic

ResultDisplayViewModel -[hidden]left- CommandBoxViewModel
PersonListViewModel -[hidden]left- ResultDisplayViewModel
MeetingListViewModel -[hidden]left- PersonListViewModel
@enduml
